CREATE TABLE IF NOT EXISTS `b_ynsir_candidate` (
  `ID` int(18) NOT NULL AUTO_INCREMENT,
  `MODIFIED_DATE` timestamp DEFAULT current_timestamp ON UPDATE current_timestamp,
  `CREATED_DATE` timestamp NOT NULL,
  `USER_ID` int(10) DEFAULT NULL,
  `CREATED_BY` int(10) NOT NULL,
  `MODIFIED_BY` int(10) NOT NULL,
  `SALT_NAME` int(6) DEFAULT NULL,
  `FIRST_NAME` varchar(50) DEFAULT NULL,
  `GENDER` varchar(50) DEFAULT NULL,
  `MARITAL_STATUS` varchar(50) DEFAULT NULL,
  `LAST_NAME` varchar(50) NOT NULL,
--   `EMAIL` varchar(50) DEFAULT NULL,
--   `CMOBILE` varchar(20) DEFAULT NULL,
--   `PHONE` varchar(20) DEFAULT NULL,
  `DOB` date DEFAULT NULL,
  `WEBSITE` varchar(100) DEFAULT NULL,
  `EXPERIENCE` int(2) DEFAULT NULL,
  `TYPE_OF_EMPLOYMENT` int(6) DEFAULT NULL,
--   `CURRENT_JOB_TITLE` int(6) DEFAULT NULL,
  `CURRENT_EMPLOYER` varchar(250) DEFAULT NULL,
  `EXPECTED_SALARY` int(6) DEFAULT NULL,
  `CURRENT_SALARY` int(6) DEFAULT NULL,
  `SKILL_SET` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `ADDITIONAL_INFO` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `SKYPE_ID`varchar(50) DEFAULT NULL,
  `TWITTER` varchar(100) DEFAULT NULL,
  `FACEBOOK` varchar(100) DEFAULT NULL,
  `LINKEDIN` varchar(100) DEFAULT NULL,
  `CANDIDATE_STATUS` varchar(50) DEFAULT NULL,
  `SOURCE_BY` varchar(50) DEFAULT NULL,
  `CANDIDATE_OWNER`int(10) NOT NULL, # CREATED_BY
  `OMOBILE`varchar(50) DEFAULT NULL,
  `EMAIL_OPT_OUT` tinyint(1) DEFAULT 0,
  `ACTIVE` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `b_ynsir_file` (
  `ID` int(18) NOT NULL AUTO_INCREMENT,
  `CANDIDATE_ID` int(10) DEFAULT NULL,
  `TYPE` varchar(30) DEFAULT NULL, # RESUME, FORMATTED_RESUME, COVER_LETTER, OTHERS
  `FILE_ID` int(18) NOT NULL,
  `USER_UPLOAD` int(18) NOT NULL,
  `FILE_CONTENT` longtext COLLATE utf8_unicode_ci,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `b_ynsir_role` (
  `ID` int(18) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `b_ynsir_role_perms` (
  `ID` int(18) unsigned NOT NULL AUTO_INCREMENT,
  `ROLE_ID` int(18) unsigned NOT NULL,
  `ENTITY` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `FIELD` varchar(30) COLLATE utf8_unicode_ci DEFAULT '-',
  `FIELD_VALUE` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `PERM_TYPE` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `ATTR` char(1) COLLATE utf8_unicode_ci DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `IX_ROLE_ID` (`ROLE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `b_ynsir_role_relation` (
  `ID` int(18) NOT NULL AUTO_INCREMENT,
  `ROLE_ID` int(18) unsigned NOT NULL,
  `RELATION` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IX_ROLE_RELATION` (`ROLE_ID`,`RELATION`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
-- update by nhatth2@younetco.com
-- TYPE LIST CHOICE
CREATE TABLE IF NOT EXISTS `b_hrm_type_list` (
  `ID` int(18) NOT NULL AUTO_INCREMENT,
  `NAME_EN` varchar(100) NOT NULL,
  `NAME_VN` varchar(100) NOT NULL,
  `ENTITY` varchar(50) NOT NULL,
  `CODE` varchar(50) NOT NULL,
  `SORT` varchar(50) NOT NULL,
  `IN_SUGGEST` tinyint(1) unsigned DEFAULT 0,
  `ADDITIONAL_INFO` tinyint(1) DEFAULT 0,
  `COUNT` int(6) unsigned DEFAULT 0,
  `ADDITIONAL_INFO_LABEL_EN` varchar(100) DEFAULT NULL,
  `ADDITIONAL_INFO_LABEL_VN` varchar(100) DEFAULT NULL,
  `MODIFIED_DATE` timestamp DEFAULT current_timestamp ON UPDATE current_timestamp,
  `CREATED_DATE` timestamp NOT NULL,
  `CREATED_BY` int(10) NOT NULL,
  `MODIFIED_BY` int(10) NOT NULL,
  `CATEGORY` int(10) DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `b_ynsir_jo_status`
(
  ID INT (18) NOT NULL AUTO_INCREMENT,
  ENTITY_ID VARCHAR (50) NOT NULL,
  STATUS_ID VARCHAR (50) NOT NULL,
  NAME VARCHAR (100) NOT NULL,
  NAME_INIT VARCHAR (100) NULL,
  SORT INT (18) NOT NULL,
  SYSTEM CHAR (1) NOT NULL,
  PRIMARY KEY (ID),
  INDEX IX_B_CRM_STATUS (STATUS_ID, ENTITY_ID)
);
-- act
CREATE TABLE IF NOT EXISTS `b_ynsir_act` (
  `ID` int(18) unsigned NOT NULL AUTO_INCREMENT,
  `TYPE_ID` tinyint(1) unsigned NOT NULL,
  `PROVIDER_ID` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `PROVIDER_TYPE_ID` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `REFERENCE_ID` int(10) DEFAULT 0,
  `REFERENCE_TYPE_ID` varchar(100) DEFAULT NULL,
  `OWNER_ID` int(1) NOT NULL,
  `OWNER_TYPE_ID` tinyint(1) unsigned NOT NULL,
  `ASSOCIATED_ENTITY_ID` int(1) DEFAULT NULL,
  `CALENDAR_EVENT_ID` int(1) unsigned NOT NULL DEFAULT '0',
  `SUBJECT` varchar(512) COLLATE utf8_unicode_ci NOT NULL,
  `COMPLETED` char(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'N',
  `RESPONSIBLE_ID` int(1) NOT NULL,
  `PRIORITY` int(1) NOT NULL,
  `NOTIFY_TYPE` int(1) NOT NULL,
  `PARENT_AUTO_ID` int(18) DEFAULT NULL,
  `ROUND_ID` int(18) DEFAULT NULL,
  `NOTIFY_VALUE` int(1) unsigned DEFAULT NULL,
  `DESCRIPTION` longtext COLLATE utf8_unicode_ci,
  `DESCRIPTION_TYPE` tinyint(1) unsigned DEFAULT NULL,
  `DIRECTION` tinyint(1) unsigned NOT NULL,
  `LOCATION` varchar(256) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CREATED` datetime NOT NULL,
  `LAST_UPDATED` datetime NOT NULL,
  `START_TIME` datetime DEFAULT NULL,
  `END_TIME` datetime DEFAULT NULL,
  `DEADLINE` datetime DEFAULT NULL,
  `STORAGE_TYPE_ID` tinyint(1) unsigned DEFAULT NULL,
  `STORAGE_ELEMENT_IDS` text COLLATE utf8_unicode_ci,
  `PARENT_ID` int(1) unsigned NOT NULL DEFAULT '0',
  `URN` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `SETTINGS` text COLLATE utf8_unicode_ci,
  `ORIGINATOR_ID` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ORIGIN_ID` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `AUTHOR_ID` int(1) unsigned DEFAULT NULL,
  `EDITOR_ID` int(1) unsigned DEFAULT NULL,
  `PROVIDER_PARAMS` longtext COLLATE utf8_unicode_ci,
  `PROVIDER_DATA` longtext COLLATE utf8_unicode_ci,
  `RESULT_STATUS` int(1) NOT NULL DEFAULT '0',
  `RESULT_STREAM` int(1) NOT NULL DEFAULT '0',
  `RESULT_SOURCE_ID` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `RESULT_MARK` int(1) NOT NULL DEFAULT '0',
  `RESULT_VALUE` decimal(18,4) DEFAULT NULL,
  `RESULT_SUM` decimal(18,4) DEFAULT NULL,
  `RESULT_CURRENCY_ID` char(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `THREAD_ID` int(1) unsigned NOT NULL DEFAULT '0',
  `PROVIDER_GROUP_ID` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `STATUS` int(1) unsigned NOT NULL DEFAULT '0',
  `SEARCH_CONTENT` mediumtext COLLATE utf8_unicode_ci,
  `AUTOCOMPLETE_RULE` int(1) unsigned NOT NULL DEFAULT '0',
  `ATTENDEES_CODES` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `IX_B_YNSIR_ACT` (`ID`,`PARENT_ID`,`OWNER_ID`,`OWNER_TYPE_ID`),
  KEY `IX_B_YNSIR_ACT_1` (`RESPONSIBLE_ID`,`COMPLETED`,`DEADLINE`),
  KEY `IX_B_YNSIR_ACT_2` (`ASSOCIATED_ENTITY_ID`,`TYPE_ID`),
  KEY `IX_B_YNSIR_ACT_4` (`DEADLINE`),
  KEY `IX_B_YNSIR_ACT_5` (`ORIGIN_ID`),
  KEY `IX_B_YNSIR_ACT_6` (`TYPE_ID`,`COMPLETED`,`DEADLINE`,`ID`),
  KEY `IX_B_YNSIR_ACT_7` (`OWNER_ID`,`OWNER_TYPE_ID`,`TYPE_ID`,`COMPLETED`,`DEADLINE`,`ID`),
  KEY `IX_B_YNSIR_ACT_8` (`PROVIDER_ID`),
  KEY `IX_B_YNSIR_ACT_9` (`CALENDAR_EVENT_ID`),
  KEY `IX_B_YNSIR_ACT_10` (`URN`),
  KEY `IX_B_YNSIR_ACT_11` (`PARENT_ID`),
  KEY `IX_B_YNSIR_ACT_12` (`THREAD_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- user act bind
CREATE TABLE IF NOT EXISTS `b_ynsir_act_bind` (
  `ID` int(18) unsigned NOT NULL AUTO_INCREMENT,
  `ACTIVITY_ID` int(1) NOT NULL,
  `OWNER_ID` int(1) NOT NULL,
  `OWNER_TYPE_ID` tinyint(1) unsigned NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IX_B_YNSIR_ACT_BIND_1` (`ACTIVITY_ID`),
  KEY `IX_B_YNSIR_ACT_BIND_2` (`OWNER_ID`,`OWNER_TYPE_ID`,`ACTIVITY_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Table structure for table `b_ynsir_act_channel_stat`
--

CREATE TABLE IF NOT EXISTS `b_ynsir_act_channel_stat` (
  `OWNER_ID` int(18) unsigned NOT NULL,
  `CREATED_DATE` date NOT NULL,
  `CHANNEL_TYPE_ID` tinyint(1) unsigned NOT NULL,
  `CHANNEL_ORIGIN_ID` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CHANNEL_COMPONENT_ID` varchar(32) COLLATE utf8_unicode_ci DEFAULT NULL,
  `RESPONSIBLE_ID` int(1) unsigned NOT NULL,
  `COMPLETED` char(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'N',
  PRIMARY KEY (`OWNER_ID`,`CHANNEL_TYPE_ID`),
  KEY `IX_B_YNSIR_ACT_CHANNEL_STAT_1` (`CHANNEL_TYPE_ID`,`CHANNEL_ORIGIN_ID`,`CHANNEL_COMPONENT_ID`,`CREATED_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Table structure for table `b_ynsir_act_comm`
--

CREATE TABLE IF NOT EXISTS `b_ynsir_act_comm` (
  `ID` int(18) unsigned NOT NULL AUTO_INCREMENT,
  `ACTIVITY_ID` int(1) unsigned NOT NULL,
  `OWNER_ID` int(1) NOT NULL,
  `OWNER_TYPE_ID` tinyint(1) unsigned NOT NULL,
  `TYPE` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `VALUE` varchar(256) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ENTITY_ID` int(1) unsigned NOT NULL,
  `ENTITY_TYPE_ID` tinyint(1) unsigned NOT NULL,
  `ENTITY_SETTINGS` text COLLATE utf8_unicode_ci,
  PRIMARY KEY (`ID`),
  KEY `IX_B_YNSIR_ACT_COMM` (`ACTIVITY_ID`,`OWNER_ID`,`OWNER_TYPE_ID`,`ENTITY_ID`,`ENTITY_TYPE_ID`),
  KEY `IX_B_YNSIR_ACT_COMM_2` (`ENTITY_ID`,`ENTITY_TYPE_ID`,`ID`),
  KEY `IX_B_YNSIR_ACT_COMM_3` (`OWNER_ID`,`OWNER_TYPE_ID`,`TYPE`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Table structure for table `b_ynsir_act_elem`
--

CREATE TABLE IF NOT EXISTS `b_ynsir_act_elem` (
  `ACTIVITY_ID` int(18) unsigned NOT NULL,
  `STORAGE_TYPE_ID` tinyint(1) unsigned NOT NULL,
  `ELEMENT_ID` int(1) unsigned NOT NULL,
  PRIMARY KEY (`ACTIVITY_ID`,`STORAGE_TYPE_ID`,`ELEMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Table structure for table `b_ynsir_act_mail_meta`
--

CREATE TABLE IF NOT EXISTS `b_ynsir_act_mail_meta` (
  `ACTIVITY_ID` int(10) unsigned NOT NULL,
  `MSG_ID_HASH` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MSG_HEADER_HASH` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  `MSG_INREPLY_HASH` varchar(40) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ACTIVITY_ID`),
  KEY `IX_B_YNSIR_ACT_MAIL_META_1` (`MSG_ID_HASH`),
  KEY `IX_B_YNSIR_ACT_MAIL_META_2` (`MSG_HEADER_HASH`),
  KEY `IX_B_YNSIR_ACT_MAIL_META_3` (`MSG_INREPLY_HASH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Table structure for table `b_ynsir_act_stat`
--

CREATE TABLE IF NOT EXISTS `b_ynsir_act_stat` (
  `OWNER_ID` int(1) unsigned NOT NULL,
  `DEADLINE_DATE` date NOT NULL,
  `PROVIDER_ID` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `PROVIDER_TYPE_ID` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `RESPONSIBLE_ID` int(1) unsigned NOT NULL,
  `COMPLETED` char(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  `STATUS_ID` int(1) unsigned DEFAULT NULL,
  `MARK_ID` int(1) unsigned DEFAULT NULL,
  `SOURCE_ID` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `STREAM_ID` int(1) unsigned DEFAULT NULL,
  `CURRENCY_ID` char(3) COLLATE utf8_unicode_ci DEFAULT NULL,
  `SUM_TOTAL` decimal(18,4) DEFAULT NULL,
  PRIMARY KEY (`OWNER_ID`,`DEADLINE_DATE`,`PROVIDER_ID`,`PROVIDER_TYPE_ID`),
  KEY `IX_B_YNSIR_ACT_STAT_1` (`RESPONSIBLE_ID`,`DEADLINE_DATE`,`OWNER_ID`,`PROVIDER_ID`,`PROVIDER_TYPE_ID`,`COMPLETED`),
  KEY `IX_B_YNSIR_ACT_STAT_2` (`DEADLINE_DATE`,`OWNER_ID`,`PROVIDER_ID`,`PROVIDER_TYPE_ID`,`COMPLETED`),
  KEY `IX_B_YNSIR_ACT_STAT_5` (`RESPONSIBLE_ID`,`DEADLINE_DATE`,`OWNER_ID`,`PROVIDER_ID`,`PROVIDER_TYPE_ID`,`STATUS_ID`),
  KEY `IX_B_YNSIR_ACT_STAT_6` (`DEADLINE_DATE`,`OWNER_ID`,`PROVIDER_ID`,`PROVIDER_TYPE_ID`,`STATUS_ID`),
  KEY `IX_B_YNSIR_ACT_STAT_7` (`RESPONSIBLE_ID`,`DEADLINE_DATE`,`OWNER_ID`,`PROVIDER_ID`,`PROVIDER_TYPE_ID`,`STREAM_ID`),
  KEY `IX_B_YNSIR_ACT_STAT_8` (`DEADLINE_DATE`,`OWNER_ID`,`PROVIDER_ID`,`PROVIDER_TYPE_ID`,`STREAM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--usr act
CREATE TABLE IF NOT EXISTS `b_ynsir_usr_act` (
  `USER_ID` int(1) unsigned NOT NULL,
  `OWNER_ID` int(1) NOT NULL,
  `OWNER_TYPE_ID` tinyint(1) unsigned NOT NULL,
  `ACTIVITY_TIME` datetime NOT NULL,
  `ACTIVITY_ID` int(1) unsigned NOT NULL,
  `DEPARTMENT_ID` int(1) unsigned NOT NULL,
  `SORT` varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`USER_ID`,`OWNER_ID`,`OWNER_TYPE_ID`),
  KEY `IX_B_YNSIR_USR_ACT` (`USER_ID`,`OWNER_ID`,`OWNER_TYPE_ID`,`ACTIVITY_TIME`,`ACTIVITY_ID`,`DEPARTMENT_ID`),
  KEY `IX_B_YNSIR_USR_ACT_2` (`OWNER_ID`,`OWNER_TYPE_ID`,`USER_ID`,`SORT`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- event
CREATE TABLE IF NOT EXISTS `b_ynsir_event` (
  `ID` int(18) NOT NULL AUTO_INCREMENT,
  `DATE_CREATE` datetime NOT NULL,
  `CREATED_BY_ID` int(18) NOT NULL,
  `EVENT_ID` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `EVENT_NAME` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `EVENT_TEXT_1` text COLLATE utf8_unicode_ci,
  `EVENT_TEXT_2` text COLLATE utf8_unicode_ci,
  `EVENT_TYPE` int(11) DEFAULT NULL,
  `FILES` text COLLATE utf8_unicode_ci,
  PRIMARY KEY (`ID`),
  KEY `IX_EVENT_1` (`DATE_CREATE`),
  KEY `IX_B_YNSIR_EVENT_2` (`EVENT_TYPE`,`EVENT_ID`,`ID`),
  KEY `IX_B_YNSIR_EVENT_3` (`CREATED_BY_ID`,`ID`),
  KEY `IX_B_YNSIR_EVENT_4` (`EVENT_TYPE`,`DATE_CREATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
-- event relations
CREATE TABLE IF NOT EXISTS `b_ynsir_mail_template`(
  ID INT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  OWNER_ID INT(1) NOT NULL,
  ENTITY_TYPE_ID TINYINT(1) UNSIGNED NOT NULL,
  SCOPE TINYINT(1) UNSIGNED NOT NULL,
  IS_ACTIVE CHAR(1) NOT NULL DEFAULT 'N',
  TITLE VARCHAR(128),
  EMAIL_FROM VARCHAR(255),
  SUBJECT VARCHAR(255),
  BODY TEXT,
  SING_REQUIRED CHAR(1) NOT NULL DEFAULT 'N',
  SORT INT(1) NOT NULL DEFAULT 100,
  CREATED DATETIME NOT NULL,
  LAST_UPDATED DATETIME NOT NULL,
  AUTHOR_ID INT(1) UNSIGNED NOT NULL,
  EDITOR_ID INT(1) UNSIGNED NOT NULL,
  PRIMARY KEY(ID),
  INDEX IX_B_YNSIR_USR_MT(OWNER_ID, ENTITY_TYPE_ID, SCOPE, IS_ACTIVE)
);
CREATE TABLE IF NOT EXISTS `b_ynsir_event_relations` (
  `ID` int(18) NOT NULL AUTO_INCREMENT,
  `ASSIGNED_BY_ID` int(18) NOT NULL,
  `ENTITY_TYPE` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `ENTITY_ID` int(11) NOT NULL,
  `ENTITY_FIELD` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `EVENT_ID` int(18) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IX_EVENT_REL_ENTITY` (`ENTITY_TYPE`,`ENTITY_ID`,`ENTITY_FIELD`),
  KEY `IX_EVENT_REL_1` (`EVENT_ID`),
  KEY `IX_EVENT_REL_2` (`ENTITY_TYPE`,`ENTITY_ID`,`EVENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE IF NOT EXISTS `b_ynsir_entity_perms` (
  `ID` int(18) unsigned NOT NULL AUTO_INCREMENT,
  `ENTITY` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `ENTITY_ID` int(18) NOT NULL,
  `ATTR` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `TYPE` varchar(50) NOT NULL,
  `SOURCE` varchar(50) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `IX_ENTITY_ATTR` (`ENTITY`,`ENTITY_ID`,`ATTR`),
  KEY `IX_ENTITY_ATTR_1` (`ENTITY`,`ATTR`,`ENTITY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--usr act attendees
CREATE TABLE IF NOT EXISTS `b_ynsir_usr_act_attendees` (
  `ID` int(18) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(1) unsigned NOT NULL,
  `ACTIVITY_ID` int(1) NOT NULL,
  `CREATED_AT` datetime NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `b_ynsir_candidate_field_multiple` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `CANDIDATE_ID` int(18) NOT NULL, # Mã nhân viên
  `NAME` varchar(250) DEFAULT NULL, # Interviewer ID | HR_ID | Tên vị trí đã applied
  `CONTENT` text COLLATE utf8_unicode_ci DEFAULT NULL, # Nội dung khác nếu có
  `TYPE` varchar(50) NOT NULL,
  `ADDITIONAL_VALUE` varchar(250) DEFAULT NULL,
  `ADDITIONAL_TYPE` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `b_ynsir_job_order_template` (
  `ID` int(5) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` int(10) NOT NULL,
  `MODIFIED_BY` int(10) NOT NULL,
  `CONTENT_TEMPLATE` text COLLATE utf8_unicode_ci NOT NULL,
  `NAME_TEMPLATE` varchar(100) NOT NULL,
  `CATEGORY` int(10) NOT NULL,
  `ACTIVE` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- associate job
--
CREATE TABLE IF NOT EXISTS `b_ynsir_associate_job` (
  `ID` int(1) NOT NULL AUTO_INCREMENT,
  `CANDIDATE_ID` int(1) unsigned NOT NULL,
  `ORDER_JOB_ID` int(1) NOT NULL,
  `STATUS_ID` varchar(50) DEFAULT NULL,
  `STATUS_ROUND_ID` int(1) NOT NULL,
  `MODIFIED_DATE` timestamp DEFAULT current_timestamp ON UPDATE current_timestamp,
  `CREATED_DATE` timestamp NOT NULL,
  `CREATED_BY` int(10) NOT NULL,
  `MODIFIED_BY` int(10) NOT NULL,
  `SEARCH_CONTENT` TEXT COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


CREATE TABLE IF NOT EXISTS `b_ynsir_job_order` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` INT(10) NOT NULL,
  `MODIFIED_BY` INT(10) NOT NULL,
  `DATE_CREATE` DATETIME NULL,
  `DATE_MODIFY` DATETIME NULL,
  `HEADCOUNT` INT(5) NOT NULL,
  `TITLE` varchar(100) NOT NULL,
  `LEVEL` INT(10) DEFAULT NULL,
  `DEPARTMENT` INT(5) NOT NULL,
  `EXPECTED_END_DATE` DATETIME NOT NULL,
  `STATUS` VARCHAR(50) NOT NULL,
  `VACANCY_REASON` TEXT COLLATE utf8_unicode_ci DEFAULT NULL,
  `IS_REPLACE` TINYINT(1) DEFAULT 0,
  `SALARY_FROM` INT(10) DEFAULT NULL,
  `SALARY_TO` INT(10) DEFAULT NULL,
  `NOTE_SALARY` VARCHAR(250) DEFAULT NULL,
  `TEMPLATE_ID` INT(10) DEFAULT NULL,
  `DESCRIPTION` TEXT COLLATE utf8_unicode_ci DEFAULT NULL,
  `EXTEND_TEMPLATE` TINYINT(1) DEFAULT 0,
  `WF_ELEMENT` INT(10) DEFAULT 0,
  `SEARCH_CONTENT` TEXT COLLATE utf8_unicode_ci DEFAULT NULL,
  `ACTIVE` TINYINT(1) DEFAULT 1,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

# supervisor, participants, subordinates, owner, recruiter
CREATE TABLE IF NOT EXISTS `b_ynsir_user_relation` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `SOURCE_ID` INT(10) NOT NULL,
  `USER_ID` INT(10) NOT NULL,
  `ENTITY` VARCHAR(100) NOT NULL,
  `NOTE` VARCHAR(250) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `b_ynsir_interview_round` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` INT(10) NOT NULL,
  `MODIFIED_BY` INT(10) NOT NULL,
  `DATE_CREATE` DATETIME NULL,
  `DATE_MODIFY` DATETIME NULL,
  `JOB_ORDER` INT(10) NOT NULL,
  `ROUND_INDEX` TINYINT(1) NOT NULL,
  `NOTE` VARCHAR(250) DEFAULT NULL,
  `SEARCH_CONTENT` TEXT COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE IF NOT EXISTS `b_ynsir_bp_perms` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `USER_ID` INT(10) NOT NULL,
  `ELEMENT_ID` INT(10) NOT NULL,
  `ENTITY` VARCHAR(100) NOT NULL,
  `DATE_CREATE` DATETIME NULL,
  `DATE_MODIFY` DATETIME NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `b_ynsir_feedback` (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `CREATED_BY` INT(10) NOT NULL,
  `MODIFIED_BY` INT(10) NOT NULL,
  `MODIFIED_DATE` DATETIME NULL,
  `CREATED_DATE` DATETIME NULL,
  `CANDIDATE_ID` INT(5) NOT NULL,
  `JOB_ORDER_ID` INT(5) NOT NULL,
  `ROUND_ID` INT(5) NOT NULL,
  `TITLE` varchar(100) NOT NULL,
  `DESCRIPTION` longtext COLLATE utf8_unicode_ci,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
